import { Suspense } from 'react'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Loading from '../components/Loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Samboleap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Suspense fallback={<Loading/>}>
        {children}
        <Footer />
        </Suspense>
      </body>
    </html>
  )
}
